name: Trigger Quartz Build

on:
  push:
    branches:
      - main  # CHECK THIS: Make sure your default branch is 'main' or 'master'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Fire Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.QUARTZ_TOKEN }}
          repository: ondcerm019/PDO_EnvisAva_Quartz
          event-type: update-content